### ISSUE TITLE
Resolution of image is very bad?

### ISSUE THREAD

**Issue by imTefa** [hzitoun/android-camera2-secret-picture-taker#1]
http://imgur.com/a/33PCy
as you can see it takes photo with very bad resolution.
any help.
**[Edit]**
I tried other phones and it works fine, I take this bad images on Huawei Y6II only and I don't know why? the phone camera is 13 mpx and works fine with native camera app.

**Comment by hzitoun** [comment]
Can you paste android and kernel versions of that phone ?
