### ISSUE TITLE
VerifyError?

### ISSUE THREAD

**Issue by EXJUSTICE** [hzitoun/android-camera2-secret-picture-taker#2]
Hello,

I've been trying to understand your code as an android novice. But when running it locally on android studio, I get a verify error at

`PictureService service =new PictureService();
                        service.startCapturing(PictureActivity.this, PictureActivity.this);`

Any help is appreciated

**Comment by hzitoun** [comment]
Hum I can't tell you big thing unless you give me the whole error message displayed by your Android Studio.

But, before making any changes to the project, when you've first imported it to android studio, have you got any error?

**Comment by EXJUSTICE** [comment]
I think I figured it out, I was running it on kitkat!
Time to get a new device haha
