### ISSUE TITLE
android.hardware.camera2.CameraAccessException: The camera device is in use already

### ISSUE THREAD

**Issue by wpinfotech** [hzitoun/android-camera2-secret-picture-taker#6]
Problem while capture photo

PictureService:  exception occurred while opening camera 0
                                                                                    android.hardware.camera2.CameraAccessException: The camera device is in use already

**Comment by hzitoun** [comment]
Please explain how you got this issue and the steps to reproduce it.

**Comment by akashsoni143786** [comment]
when i try to start my flash light in camera2
and use a value
 mCameraManager = (CameraManager) getActivity().getSystemService(Context.CAMERA_SERVICE);
                    try {
                        mCameraId = mCameraManager.getCameraIdList()[0];
                    } catch (CameraAccessException e) {
                        e.printStackTrace();
                    }
try {
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                            mCameraManager.setTorchMode(mCameraId, true);
// here i'm getting this error android.hardware.camera2.CameraAccessException: The camera device is in use already
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
