### ISSUE TITLE
Capture black and dark images

### ISSUE THREAD

**Issue by lequangliem** [hzitoun/android-camera2-secret-picture-taker#8]
I tried run this project on Galaxy S6 Docomo (SC-05G) installed Android 5.0.2.
Back and Front camera captured black images.
Please check it, and sorry about my english.

**Comment by hzitoun** [comment]
Please explain how you got this issue and the steps to reproduce it.

**Comment by limitlessisa** [comment]
Samsung S7 Edge, Download zip to Buid 
Result:
![screenshot_20170623-130306](https://user-images.githubusercontent.com/12773794/27477622-612f7828-5815-11e7-99a9-e78476d1d80e.jpg)

**Comment by hzitoun** [comment]
looks like your camera doesn't have time to be fully opened and capture all light before taking the picture. Try increasing the wait time in the service before taking a picture

**Comment by AantonM** [comment]
I am having the same problem. In the PictureCapturingServiceImpl class, this is the method to which I increased the wait time

`    private final CameraDevice.StateCallback stateCallback = new CameraDevice.StateCallback() {
        @Override
        public void onOpened(@NonNull CameraDevice camera) {
            cameraClosed = false;
            Log.d(TAG, "camera " + camera.getId() + " opened");
            cameraDevice = camera;
            Log.i(TAG, "Taking picture from camera " + camera.getId());
            //Take the picture after some delay. It may resolve getting a black dark photos.
            Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    try {
                        takePicture();
                    } catch (final CameraAccessException e) {
                        Log.e(TAG, " exception occurred while taking picture from " + currentCameraId, e);
                    }
                }
            }, 1000);
        }`

But the image taken is still black.
